name: 'supabase request'
on:
  schedule: 
    - cron: '5 * * * *'
jobs:
  request_api:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: sbp_33b56a132debe60f169ed4e7d43d8a900efb3b70
      SUPABASE_URL: ${{secrets.SUPABASE_URL}}
      SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
    steps:
     - name: Checkout actions
       uses: actions/checkout@v3

     - name: Supabase setup
       uses: supabase/setup-cli@v1
       with:
         version: latest
         
     - name: Init Supabase
       run: supabase init
      
     - name: Start Supabase
       run: supabase start

     - name: Curl cards
       run: |
         curl https://zrzdptljtpgfutrzaqfq.supabase.co
              
